---
- name: Ensure that the transmission-daemon package is installed
  tags: transmission-daemon
  become: true
  yum:
    enablerepo: epel
    name: "{{ item }}"
    state: present
  register: transmission_daemon_yum
  with_items:
    - libnatpmp
    - transmission-daemon

- name: Attempting to import transmission-daemon tasks
  tags: transmission-daemon
  become: true
  block:
    - import_tasks: td_groupmod.yml
    - import_tasks: td_configuration.yml
    - import_tasks: td_service.yml
    - import_tasks: td_blocklist.yml
  when: transmission_daemon_yum is success
...
