---
- name: Ensure that the transmission-daemon package is installed
  tags: transmission-daemon
  become: true
  yum:
    enablerepo: epel
    name: "{{ item }}"
    state: present
  register: transmission_daemon_yum
  with_items:
    - libnatpmp
    - transmission-daemon

- block:
    - name: Ensure that the transmission configuration and download directories exists
      file:
        path: "{{ item }}"
        owner: transmission
        group: transmission
        mode: 0755
        state: directory
      with_items:
        - /var/lib/transmission/.config
        - /var/lib/transmission/.config/transmission-daemon
        - "{{ td_download_dir }}"
        - "{{ td_incomplete_dir }}"

    - name: Applying transmission-daemon configuration
      template:
        src: settings.json.j2
        dest: /var/lib/transmission/.config/transmission-daemon/settings.json
        owner: transmission
        group: transmission
        mode: 0600
      notify: reload transmission-daemon

    - name: Enable and start transmission-daemon
      service:
        enabled: yes
        name: transmission-daemon
        state: started
  tags: transmission-daemon
  become: true
  when: transmission_daemon_yum|success
...
