---
- name: Ensure that the transmission-daemon package is installed
  tags: transmission-daemon
  become: true
  yum:
    enablerepo: epel
    name: "{{ item }}"
    state: present
  register: transmission_daemon_yum
  with_items:
    - libnatpmp
    - transmission-daemon

- block:
    - name: Ensure that the transmission configuration and download directories exists
      file:
        path: "{{ item.path }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: 0755
        state: directory
      with_items:
        - { path: "{{ td_download_dir }}", owner: transmission, group: transmission }
        - { path: "{{ td_incomplete_dir }}", owner: transmission, group: transmission }
        - { path: /etc/systemd/system/transmission-daemon.service.d, owner: root, group: root }
        - { path: /var/lib/transmission/.config, owner: transmission, group: transmission }
        - { path: /var/lib/transmission/.config/transmission-daemon, owner: transmission, group: transmission }

    - name: Applying transmission-daemon configuration
      template:
        src: settings.json.j2
        dest: /var/lib/transmission/.config/transmission-daemon/settings.json
        owner: transmission
        group: transmission
        mode: 0600
      notify: reload transmission-daemon

    - name: Enable and start transmission-daemon
      service:
        enabled: yes
        name: transmission-daemon
        state: started
      when: td_service_enabled|bool
  tags: transmission-daemon
  become: true
  when: transmission_daemon_yum|success
...
