---
- name: Attempting to import tranmission-daemon installation tasks (Debian)
  tags: transmission_daemon
  become: true
  import_tasks: td_os_debian.yml
  when: ansible_os_family == 'Debian'

- name: Attempting to import tranmission-daemon installation tasks (RedHat)
  tags: transmission_daemon
  become: true
  import_tasks: td_os_redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Attempting to import transmission-daemon configuration tasks
  tags: transmission_daemon
  become: true
  block:
    - import_tasks: td_groupmod.yml
    - import_tasks: td_configuration.yml
    - import_tasks: td_service.yml
    - import_tasks: td_blocklist.yml
    - import_tasks: td_torrents.yml
  when: transmission_daemon_package is success
...
