---
- name: Ensure that the transmission-daemon configuration directories exists
  file:
    path: "{{ item }}"
    owner: "{{ td_owner }}"
    group: "{{ td_group }}"
    mode: 0755
    state: directory
  register: transmission_daemon_file
  with_items:
    - "{{ td_download_dir }}"
    - "{{ td_incomplete_dir }}"
    - "{{ td_settings|dirname }}"
    - /var/lib/transmission/.config
    - /var/lib/transmission/.config/transmission-daemon

- name: Attempting to overlay transmission-daemon configuration
  template:
    src: settings.json.j2
    dest: "{{ td_settings }}"
    owner: "{{ td_owner }}"
    group: "{{ td_group }}"
    mode: 0600
  notify: reload transmission-daemon
  register: transmission_daemon_template
  when: transmission_daemon_file is success
...
