---
- name: Attempting to set os family specific facts (RedHat)
  become: false
  set_fact:
    td_owner: transmission
    td_group: transmission
    td_settings: /var/lib/transmission/.config/transmission-daemon/settings.json

- name: Ensure that the transmission-daemon package is installed (RedHat)
  yum:
    enablerepo: epel
    name: "{{ item }}"
    state: present
  register: transmission_daemon_yum
  with_items:
    - libnatpmp
    - transmission-daemon
...
