---
- name: Attempting to create temporary directory, if applicable
  become: false
  tempfile:
    prefix: 'transmission-daemon.'
    state: directory
  register: transmission_daemon_tempfile
  when: td_torrents|length > 0

- name: Attempting to fetch torrent files, if applicable
  become: false
  get_url:
    dest: "{{ transmission_daemon_tempfile.path }}"
    url: "{{ item }}"
  register: transmission_daemon_get_url
  with_items: "{{ td_torrents }}"
  when:
    - td_torrents|length > 0
    - transmission_daemon_tempfile is success

- name: Attempting to send torrents to transmission-daemon, if applicable
  become: false
  command: |
    /usr/bin/transmission-remote {{ td_rpc_bind_address }}:{{ td_rpc_port }} --add {{ item.dest }}
  with_items: "{{ transmission_daemon_get_url.results }}"
  when:
    - item.dest is defined
    - td_torrents|length > 0
    - transmission_daemon_service is success

- name: Attempting to purge temporary directory from filesystem
  become: false
  file:
    path: "{{ transmission_daemon_tempfile.path }}"
    state: absent
  when: transmission_daemon_tempfile is success
...
