---
- name: Attempting to download torrents, if applicable
  become: false
  command: |
    /usr/bin/transmission-remote {{ td_rpc_bind_address }}:{{ td_rpc_port }} --add {{ item }}
  with_items: "{{ td_torrents }}"
  when:
    - td_torrents|length > 0
    - transmission_daemon_service is success
...
